### ISSUE TITLE
We need to make sure we introduce them to nano

### ISSUE THREAD

**Issue by ldutoit** [otagomohio/2019-06-11_GBS_EE#1]

**Comment by laninsky** [comment]
Nano gets covered in [Working With Files and Directories](https://swcarpentry.github.io/shell-novice/03-create/index.html) during the introduction to command line lesson, so think we are good there.

**Comment by ldutoit** [comment]
Saw that yes, thanks. the only thing that I will add to bash is a simple
slurm script.

We will do one step on day 2 through slurm ( just one, I think it will be
good).
